#ifndef __USART_CONFIG_H
#define	__USART_CONFIG_H

#define TEST_USART								USART3
#define TEST_USART_CLS						RCC_APB1Periph_USART3
#define TEST_USART_BAUD						9600

#define TEST_USART_TXD_PIN				GPIO_Pin_8
#define TEST_USART_TXD_GPIO_PORT	GPIOD
#define TEST_USART_TXD_CLK				RCC_APB2Periph_GPIOD

#define TEST_USART_RXD_PIN				GPIO_Pin_9
#define TEST_USART_RXD_GPIO_PORT  GPIOD
#define TEST_USART_RXD_CLK				RCC_APB2Periph_GPIOD

#define USART_IRQ									USART3_IRQn

#endif /* __USART_CONFIG_H */
